
/***************************************************************************************************
| H | O | R | I | Z | O | N |   | L | A | B | S | 

Demo:         Horizon Lab
Version:      HLab v1
Create Date:  Apr 17, 2024
Author:       Ravi Kumar
Reviewers:    Ben Weiss, Susan Devitt
Copyright(c): 2024 Snowflake Inc. All rights reserved.
****************************************************************************************************/
/****************************************************************************************************
SUMMARY OF CHANGES
Date(yyyy-mm-dd)    Author              Comments
------------------- ------------------- ------------------------------------------------------------
Apr 17, 2024        Ravi Kumar           Initial Lab
***************************************************************************************************/
/*----------------------------------------------------------------------------------
 V A R I A B L E S
----------------------------------------------------------------------------------*/





/*----------------------------------------------------------------------------------
 C R E A T E   R O L E S
----------------------------------------------------------------------------------*/
USE ROLE SECURITYADMIN;

CREATE OR REPLACE ROLE HRZN_DATA_ENGINEER;
CREATE OR REPLACE ROLE HRZN_DATA_GOVERNOR;
CREATE OR REPLACE ROLE HRZN_DATA_USER;
CREATE OR REPLACE ROLE HRZN_IT_ADMIN;

-- Grant roles to SYSADMIN for administration
GRANT ROLE HRZN_DATA_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE HRZN_DATA_GOVERNOR TO ROLE SYSADMIN;
GRANT ROLE HRZN_DATA_USER TO ROLE SYSADMIN;
GRANT ROLE HRZN_IT_ADMIN TO ROLE SYSADMIN;

-- Grant roles to current user
GRANT ROLE HRZN_DATA_ENGINEER TO USER CURRENT_USER();
GRANT ROLE HRZN_DATA_GOVERNOR TO USER CURRENT_USER();
GRANT ROLE HRZN_DATA_USER TO USER CURRENT_USER();
GRANT ROLE HRZN_IT_ADMIN TO USER CURRENT_USER();
/*----------------------------------------------------------------------------------
 C R E A T E   W A R E H O U S E
----------------------------------------------------------------------------------*/
USE ROLE SYSADMIN;

CREATE OR REPLACE WAREHOUSE HRZN_WH WITH WAREHOUSE_SIZE='X-SMALL';

GRANT USAGE ON WAREHOUSE HRZN_WH TO ROLE HRZN_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE HRZN_WH TO ROLE HRZN_DATA_GOVERNOR;
GRANT USAGE ON WAREHOUSE HRZN_WH TO ROLE HRZN_DATA_USER;
GRANT USAGE ON WAREHOUSE HRZN_WH TO ROLE HRZN_IT_ADMIN;
/*----------------------------------------------------------------------------------
 C R E A T E   D A T A B A S E   &   S C H E M A S
----------------------------------------------------------------------------------*/
GRANT CREATE DATABASE ON ACCOUNT TO ROLE HRZN_DATA_ENGINEER;

USE ROLE HRZN_DATA_ENGINEER;

CREATE OR REPLACE DATABASE HRZN_DB;
CREATE OR REPLACE SCHEMA HRZN_DB.HRZN_SCH;

-- Grant permissions to GOVERNOR role
GRANT USAGE ON DATABASE HRZN_DB TO ROLE HRZN_DATA_GOVERNOR;
GRANT USAGE ON SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_GOVERNOR;
GRANT CREATE SCHEMA ON DATABASE HRZN_DB TO ROLE HRZN_DATA_GOVERNOR;
GRANT USAGE ON ALL SCHEMAS IN DATABASE HRZN_DB TO ROLE HRZN_DATA_GOVERNOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE HRZN_DB TO ROLE HRZN_DATA_GOVERNOR;
GRANT SELECT ON ALL TABLES IN SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_GOVERNOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_GOVERNOR;

-- Grant permissions to IT_ADMIN role
GRANT USAGE ON DATABASE HRZN_DB TO ROLE HRZN_IT_ADMIN;
GRANT USAGE ON SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_IT_ADMIN;
GRANT CREATE SCHEMA ON DATABASE HRZN_DB TO ROLE HRZN_IT_ADMIN;

-- Grant permissions to DATA_USER role
GRANT USAGE ON DATABASE HRZN_DB TO ROLE HRZN_DATA_USER;
GRANT USAGE ON SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_USER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE HRZN_DB TO ROLE HRZN_DATA_USER;
GRANT SELECT ON ALL TABLES IN DATABASE HRZN_DB TO ROLE HRZN_DATA_USER;
/*----------------------------------------------------------------------------------
 C R E A T E   A D D I T I O N A L   S C H E M A S
----------------------------------------------------------------------------------*/
USE ROLE HRZN_DATA_GOVERNOR;

-- Create Schema for classifiers
CREATE OR REPLACE SCHEMA HRZN_DB.CLASSIFIERS
COMMENT = 'Schema containing Classifiers';

-- Create Schema for Tags
CREATE OR REPLACE SCHEMA HRZN_DB.TAG_SCHEMA
COMMENT = 'Schema containing Tags';

-- Create ROW_POLICY_MAP table
CREATE OR REPLACE TABLE HRZN_DB.TAG_SCHEMA.ROW_POLICY_MAP
    (role STRING, state_visibility STRING);

-- Insert role mapping
INSERT INTO HRZN_DB.TAG_SCHEMA.ROW_POLICY_MAP
    VALUES ('HRZN_DATA_USER', 'MA'); 

-- Create Schema for Security Policies
CREATE OR REPLACE SCHEMA HRZN_DB.SEC_POLICIES_SCHEMA
COMMENT = 'Schema containing Security Policies';
/*----------------------------------------------------------------------------------
 G R A N T   F U T U R E   P E R M I S S I O N S
----------------------------------------------------------------------------------*/
USE ROLE SECURITYADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_GOVERNOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE HRZN_DB TO ROLE HRZN_DATA_GOVERNOR;

GRANT SELECT ON FUTURE TABLES IN SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_USER;
GRANT SELECT ON FUTURE TABLES IN DATABASE HRZN_DB TO ROLE HRZN_DATA_USER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_IT_ADMIN;
GRANT SELECT ON FUTURE TABLES IN DATABASE HRZN_DB TO ROLE HRZN_IT_ADMIN;

GRANT USAGE ON ALL SCHEMAS IN DATABASE HRZN_DB TO ROLE HRZN_IT_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE HRZN_DB TO ROLE HRZN_IT_ADMIN;
GRANT SELECT ON ALL VIEWS IN DATABASE HRZN_DB TO ROLE HRZN_IT_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_IT_ADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_IT_ADMIN;
/*----------------------------------------------------------------------------------
 G R A N T   D A T A   M E T R I C   &   G O V E R N A N C E   P E R M I S S I O N S
----------------------------------------------------------------------------------*/
USE ROLE ACCOUNTADMIN;

-- Grants for DATA_ENGINEER role
GRANT DATABASE ROLE SNOWFLAKE.DATA_METRIC_USER TO ROLE HRZN_DATA_ENGINEER;
GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE HRZN_DATA_ENGINEER;

-- Grants for DATA_GOVERNOR role
GRANT DATABASE ROLE SNOWFLAKE.GOVERNANCE_VIEWER TO ROLE HRZN_DATA_GOVERNOR;
GRANT DATABASE ROLE SNOWFLAKE.OBJECT_VIEWER TO ROLE HRZN_DATA_GOVERNOR;
GRANT DATABASE ROLE SNOWFLAKE.USAGE_VIEWER TO ROLE HRZN_DATA_GOVERNOR;
GRANT DATABASE ROLE SNOWFLAKE.DATA_METRIC_USER TO ROLE HRZN_DATA_GOVERNOR;
GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE HRZN_DATA_GOVERNOR;

-- Grants for IT_ADMIN role
GRANT DATABASE ROLE SNOWFLAKE.GOVERNANCE_VIEWER TO ROLE HRZN_IT_ADMIN;
GRANT DATABASE ROLE SNOWFLAKE.OBJECT_VIEWER TO ROLE HRZN_IT_ADMIN;
GRANT DATABASE ROLE SNOWFLAKE.USAGE_VIEWER TO ROLE HRZN_IT_ADMIN;
GRANT DATABASE ROLE SNOWFLAKE.DATA_METRIC_USER TO ROLE HRZN_IT_ADMIN;
GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE HRZN_IT_ADMIN;
/*----------------------------------------------------------------------------------
 C R E A T E   T A B L E S   &   L O A D   D A T A
----------------------------------------------------------------------------------*/
USE ROLE HRZN_DATA_ENGINEER;
USE WAREHOUSE HRZN_WH;

CREATE OR REPLACE TABLE HRZN_DB.HRZN_SCH.CUSTOMER (
    ID FLOAT,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    STREET_ADDRESS VARCHAR,
    STATE VARCHAR,
    CITY VARCHAR,
    ZIP VARCHAR,
    PHONE_NUMBER VARCHAR,
    EMAIL VARCHAR,
    SSN VARCHAR,
    BIRTHDATE VARCHAR,
    JOB VARCHAR,
    CREDITCARD VARCHAR,
    COMPANY VARCHAR,
    OPTIN VARCHAR
);

CREATE OR REPLACE TABLE HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS (
    CUSTOMER_ID VARCHAR,    
    ORDER_ID VARCHAR,    
    ORDER_TS DATE,    
    ORDER_CURRENCY VARCHAR,    
    ORDER_AMOUNT FLOAT,    
    ORDER_TAX FLOAT,    
    ORDER_TOTAL FLOAT
);

-- Load data from S3
COPY INTO HRZN_DB.HRZN_SCH.CUSTOMER
FROM s3://sfquickstarts/summit_2024_horizon_hol/CustomerDataRaw.csv
FILE_FORMAT = (TYPE = 'CSV', SKIP_HEADER = 1);

COPY INTO HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS
FROM s3://sfquickstarts/summit_2024_horizon_hol/CustomerOrders.csv
FILE_FORMAT = (TYPE = 'CSV', SKIP_HEADER = 1);

-- Grant permissions on tables
GRANT ALL ON TABLE HRZN_DB.HRZN_SCH.CUSTOMER TO ROLE HRZN_DATA_GOVERNOR;
GRANT SELECT ON TABLE HRZN_DB.HRZN_SCH.CUSTOMER TO ROLE HRZN_DATA_USER;
GRANT SELECT ON TABLE HRZN_DB.HRZN_SCH.CUSTOMER TO ROLE HRZN_IT_ADMIN;

GRANT ALL ON TABLE HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS TO ROLE HRZN_DATA_GOVERNOR;
GRANT SELECT ON TABLE HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS TO ROLE HRZN_DATA_USER;
GRANT SELECT ON TABLE HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS TO ROLE HRZN_IT_ADMIN;
/*----------------------------------------------------------------------------------
 G R A N T   P O L I C Y   P E R M I S S I O N S
----------------------------------------------------------------------------------*/
USE ROLE ACCOUNTADMIN;

GRANT APPLY TAG ON ACCOUNT TO ROLE HRZN_DATA_GOVERNOR;
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE HRZN_DATA_GOVERNOR;
GRANT APPLY ROW ACCESS POLICY ON ACCOUNT TO ROLE HRZN_DATA_GOVERNOR;
GRANT DATABASE ROLE SNOWFLAKE.CLASSIFICATION_ADMIN TO ROLE HRZN_DATA_GOVERNOR;
/*----------------------------------------------------------------------------------
 C R E A T E   L I N E A G E   T A B L E S   &   V I E W S
----------------------------------------------------------------------------------*/
USE ROLE HRZN_DATA_ENGINEER;
USE DATABASE HRZN_DB;
USE SCHEMA HRZN_DB.HRZN_SCH;
USE WAREHOUSE HRZN_WH;

-- Create state-specific customer tables
CREATE OR REPLACE TABLE HRZN_DB.HRZN_SCH.CUSTOMER_NY AS
SELECT * EXCLUDE ZIP FROM HRZN_DB.HRZN_SCH.CUSTOMER WHERE state='NY';

CREATE OR REPLACE TABLE HRZN_DB.HRZN_SCH.CUSTOMER_DC AS
SELECT * EXCLUDE ZIP FROM HRZN_DB.HRZN_SCH.CUSTOMER WHERE state='DC';

CREATE OR REPLACE TABLE HRZN_DB.HRZN_SCH.CUSTOMER_AR AS
SELECT * EXCLUDE ZIP FROM HRZN_DB.HRZN_SCH.CUSTOMER WHERE state='AR';

-- Create customer order summary view
CREATE OR REPLACE VIEW HRZN_DB.HRZN_SCH.CUSTOMER_ORDER_SUMMARY AS
SELECT C.ID, C.FIRST_NAME, C.LAST_NAME, COUNT(CO.ORDER_ID) ORDERS_COUNT, SUM(CO.ORDER_TOTAL) ORDER_TOTAL
FROM HRZN_DB.HRZN_SCH.CUSTOMER C, HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS CO
WHERE C.ID = CO.CUSTOMER_ID
GROUP BY 1,2,3;

-- Create NY customer order summary table
CREATE OR REPLACE TABLE HRZN_DB.HRZN_SCH.CUSTOMER_ORDER_SUMMARY_NY AS
SELECT CS.*
FROM HRZN_DB.HRZN_SCH.CUSTOMER_NY C, HRZN_DB.HRZN_SCH.CUSTOMER_ORDER_SUMMARY CS
WHERE C.ID = CS.ID;

-- Create stage and copy data
CREATE OR REPLACE STAGE HRZN_DB.HRZN_SCH.CUSTOMERNYSTAGE;
COPY INTO @HRZN_DB.HRZN_SCH.CUSTOMERNYSTAGE FROM HRZN_DB.HRZN_SCH.CUSTOMER_ORDER_SUMMARY_NY;
/*----------------------------------------------------------------------------------
 V E R I F Y   S E T U P
----------------------------------------------------------------------------------*/
SELECT 'Setup complete' AS STATUS;
SELECT COUNT(*) AS CUSTOMER_COUNT FROM HRZN_DB.HRZN_SCH.CUSTOMER;
SELECT COUNT(*) AS ORDER_COUNT FROM HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS;
